name: chicagomapbot

on:
  schedule:
    - cron: '15 0/1 * * *'  # once every hour in the 15th minute (for now)

jobs:
  chicagomapbot-post:
    runs-on: macos-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install geo libraries
        if: runner.os == 'macOS'
        run: | 
          brew install proj
          brew install geos
          brew install gdal
          brew install udunits
      - name: Install dependencies
        run: Rscript dependencies.R
      - name: Create and post tweet
        run: Rscript chicagomapbot.R
